# Group B: channels 11-20
# Replace every placeholder. No spaces, no quotes, no line breaks inside the lists.
# Token #1 records channel #1, token #2 records channel #2, and so on.

GUILD_ID=YOUR_SERVER_ID

CHANNEL_IDS=CHANNEL_ID_11,CHANNEL_ID_12,CHANNEL_ID_13,CHANNEL_ID_14,CHANNEL_ID_15,CHANNEL_ID_16,CHANNEL_ID_17,CHANNEL_ID_18,CHANNEL_ID_19,CHANNEL_ID_20

BOT_TOKENS=BOT_TOKEN_11,BOT_TOKEN_12,BOT_TOKEN_13,BOT_TOKEN_14,BOT_TOKEN_15,BOT_TOKEN_16,BOT_TOKEN_17,BOT_TOKEN_18,BOT_TOKEN_19,BOT_TOKEN_20

ANNOUNCE=true
BOT_NICKNAME=🔴 Recording
