# Group C: channels 21-30
# Replace every placeholder. No spaces, no quotes, no line breaks inside the lists.
# Token #1 records channel #1, token #2 records channel #2, and so on.

GUILD_ID=YOUR_SERVER_ID

CHANNEL_IDS=CHANNEL_ID_21,CHANNEL_ID_22,CHANNEL_ID_23,CHANNEL_ID_24,CHANNEL_ID_25,CHANNEL_ID_26,CHANNEL_ID_27,CHANNEL_ID_28,CHANNEL_ID_29,CHANNEL_ID_30

BOT_TOKENS=BOT_TOKEN_21,BOT_TOKEN_22,BOT_TOKEN_23,BOT_TOKEN_24,BOT_TOKEN_25,BOT_TOKEN_26,BOT_TOKEN_27,BOT_TOKEN_28,BOT_TOKEN_29,BOT_TOKEN_30

ANNOUNCE=true
BOT_NICKNAME=🔴 Recording
